// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: grpc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventBridgeService_SendEvent_FullMethodName    = "/eventsbridge.grpc.v1.EventBridgeService/SendEvent"
	EventBridgeService_StreamEvents_FullMethodName = "/eventsbridge.grpc.v1.EventBridgeService/StreamEvents"
)

// EventBridgeServiceClient is the client API for EventBridgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EventBridgeService defines the gRPC service for receiving events.
type EventBridgeServiceClient interface {
	// SendEvent sends a single event message and waits for acknowledgment
	SendEvent(ctx context.Context, in *EventMessage, opts ...grpc.CallOption) (*EventResponse, error)
	// StreamEvents sends multiple event messages via client streaming
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EventMessage, EventResponse], error)
}

type eventBridgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventBridgeServiceClient(cc grpc.ClientConnInterface) EventBridgeServiceClient {
	return &eventBridgeServiceClient{cc}
}

func (c *eventBridgeServiceClient) SendEvent(ctx context.Context, in *EventMessage, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, EventBridgeService_SendEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventBridgeServiceClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EventMessage, EventResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventBridgeService_ServiceDesc.Streams[0], EventBridgeService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventMessage, EventResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventBridgeService_StreamEventsClient = grpc.ClientStreamingClient[EventMessage, EventResponse]

// EventBridgeServiceServer is the server API for EventBridgeService service.
// All implementations must embed UnimplementedEventBridgeServiceServer
// for forward compatibility.
//
// EventBridgeService defines the gRPC service for receiving events.
type EventBridgeServiceServer interface {
	// SendEvent sends a single event message and waits for acknowledgment
	SendEvent(context.Context, *EventMessage) (*EventResponse, error)
	// StreamEvents sends multiple event messages via client streaming
	StreamEvents(grpc.ClientStreamingServer[EventMessage, EventResponse]) error
	mustEmbedUnimplementedEventBridgeServiceServer()
}

// UnimplementedEventBridgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventBridgeServiceServer struct{}

func (UnimplementedEventBridgeServiceServer) SendEvent(context.Context, *EventMessage) (*EventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEvent not implemented")
}
func (UnimplementedEventBridgeServiceServer) StreamEvents(grpc.ClientStreamingServer[EventMessage, EventResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedEventBridgeServiceServer) mustEmbedUnimplementedEventBridgeServiceServer() {}
func (UnimplementedEventBridgeServiceServer) testEmbeddedByValue()                            {}

// UnsafeEventBridgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventBridgeServiceServer will
// result in compilation errors.
type UnsafeEventBridgeServiceServer interface {
	mustEmbedUnimplementedEventBridgeServiceServer()
}

func RegisterEventBridgeServiceServer(s grpc.ServiceRegistrar, srv EventBridgeServiceServer) {
	// If the following call pancis, it indicates UnimplementedEventBridgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventBridgeService_ServiceDesc, srv)
}

func _EventBridgeService_SendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventBridgeServiceServer).SendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventBridgeService_SendEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventBridgeServiceServer).SendEvent(ctx, req.(*EventMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventBridgeService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventBridgeServiceServer).StreamEvents(&grpc.GenericServerStream[EventMessage, EventResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventBridgeService_StreamEventsServer = grpc.ClientStreamingServer[EventMessage, EventResponse]

// EventBridgeService_ServiceDesc is the grpc.ServiceDesc for EventBridgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventBridgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eventsbridge.grpc.v1.EventBridgeService",
	HandlerType: (*EventBridgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEvent",
			Handler:    _EventBridgeService_SendEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _EventBridgeService_StreamEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "grpc.proto",
}
