source:
  type: "git"
  git:
    remote_url: "http://localhost:3000/testuser/testrepo.git"
    username: "testuser"
    password: "testpass"
    remote: "origin"
    branch: "main"
    poll_interval: 10
    # subdir: "optional/subdir"

target:
  type: "http"
  http:
    method: "POST"
    url: "http://localhost:8080/api/data"

runner:
  type: "wasm"
  wasm:
    path: "./testers/bin/wasmrunner.wasm"
