source:
  type: "nats"
  nats:
    address: "localhost:4222"
    subject: "test.subject.in"

target:
  type: "nats"
  nats:
    address: "localhost:4222"
    subject: "test.subject.out"
  routines: 8

runner:
  type: "jsonlogic"
  jsonlogic:
    path: "./testers/config/bridge/jsonlogic-rule.json"
  routines: 8
