source:
  type: "nats"
  nats:
    address: "localhost:4222"
    subject: "test.subject"

target:
  type: "http"
  http:
    method: "POST"
    url: "http://localhost:8080/api/data"

runner:
  type: "wasm"
  wasm:
    path: "./testers/bin/wasmrunner.wasm"
