source:
  type: "redis"
  redis:
    address: "localhost:6379"
    channel: "test.channel.in"

target:
  type: "redis"
  redis:
    address: "localhost:6379"
    channel: "test.channel.out"

runner:
  type: "jsonlogic"
  jsonlogic:
    path: "./testers/config/bridge/jsonlogic-rule.json"
  # you can change the path or the rule as needed
