version: "3"

tasks:
  test-coap:
    cmds:
      - viddy go run ./coapclient 'localhost:5683' '/event' '{"test":123}'

  test-http:
    cmds:
      - viddy curl -X POST -H "Content-Type: application/json" -d '{"test":123}' http://localhost:8080/event

  test-nats:
    cmds:
      - viddy nats pub event.subject '{"test":123}' --server nats://localhost:4222

  test-mqtt:
    cmds:
      - viddy mosquitto_pub -h localhost -t event/topic -m '{"test":123}'

  test-kafka:
    cmds:
      - viddy kafka-console-producer --broker-list localhost:9092 --topic event_topic <<< '{"test":123}'
