version: "3"

tasks:
  build:
    cmds:
      - rm -rf ./bin
      - mkdir -p ./bin/connectors
      - mkdir -p ./bin/runners
      - go build -buildmode=plugin -o ./bin/connectors/http.so ./src/connectors/http && du -h ./bin/connectors/http.so
      - go build -buildmode=plugin -o ./bin/connectors/coap.so ./src/connectors/coap && du -h ./bin/connectors/coap.so
      - go build -buildmode=plugin -o ./bin/connectors/nats.so ./src/connectors/nats && du -h ./bin/connectors/nats.so
      - go build -buildmode=plugin -o ./bin/connectors/mqtt.so ./src/connectors/mqtt && du -h ./bin/connectors/mqtt.so
      - go build -buildmode=plugin -o ./bin/connectors/pgsql.so ./src/connectors/pgsql && du -h ./bin/connectors/pgsql.so
      - go build -buildmode=plugin -o ./bin/connectors/kafka.so ./src/connectors/kafka && du -h ./bin/connectors/kafka.so
      - go build -buildmode=plugin -o ./bin/connectors/redis.so ./src/connectors/redis && du -h ./bin/connectors/redis.so
      - go build -buildmode=plugin -o ./bin/runners/es5runner.so ./src/runners/es5runner && du -h ./bin/runners/es5runner.so
      - go build -buildmode=plugin -o ./bin/runners/wasmrunner.so ./src/runners/wasmrunner && du -h ./bin/runners/wasmrunner.so
      - go build -buildmode=plugin -o ./bin/runners/gptrunner.so ./src/runners/gptrunner && du -h ./bin/runners/gptrunner.so
      - go build -buildmode=plugin -o ./bin/runners/jlorunner.so ./src/runners/jlorunner && du -h ./bin/runners/jlorunner.so
      - go build -o ./bin/events-bridge ./src

  test-coap:
    cmds:
      - viddy go run ./coapclient 'localhost:5683' '/event' '{"test":123}'

  test-http:
    cmds:
      - 'viddy curl -X POST -H ''Content-Type: application/json'' -d ''{"test":123}'' ''http://localhost:8080/event'''

  test-nats:
    cmds:
      - viddy nats pub event.subject '{"test":123}' --server nats://localhost:4222

  gen-plugin-proto:
    dir: ./src/plugin/proto
    cmds:
      - protoc --proto_path=. --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative ./plugin.proto

  build-testers:
    dir: ./testers
    cmds:
      - mkdir -p ./bin
      - go build -o ./bin/concurrently ./concurrently && du -h ./bin/concurrently
      - go build -o ./bin/natssource ./sources/natssource && du -h ./bin/natssource
      - go build -o ./bin/coapsource ./sources/coapsource && du -h ./bin/coapsource
      - go build -o ./bin/pgsqlsource ./sources/pgsqlsource && du -h ./bin/pgsqlsource
      - go build -o ./bin/mqttsource ./sources/mqttsource && du -h ./bin/mqttsource
      - go build -o ./bin/httpsource ./sources/httpsource && du -h ./bin/httpsource
      - go build -o ./bin/kafkasource ./sources/kafkasource && du -h ./bin/kafkasource
      - go build -o ./bin/redissource ./sources/redissource && du -h ./bin/redissource
      - go build -o ./bin/mqtttarget ./targets/mqtttarget && du -h ./bin/mqtttarget
      - go build -o ./bin/kafkatarget ./targets/kafkatarget && du -h ./bin/kafkatarget
      - go build -o ./bin/coaptarget ./targets/coaptarget && du -h ./bin/coaptarget
      - go build -o ./bin/httptarget ./targets/httptarget && du -h ./bin/httptarget
      - go build -o ./bin/natstarget ./targets/natstarget && du -h ./bin/natstarget
      - go build -o ./bin/redistarget ./targets/redistarget && du -h ./bin/redistarget
      - go build -o ./bin/plugin ./plugins/plugin && du -h ./bin/plugin
      - tinygo build -o ./bin/wasmrunner.wasm -target=wasi ./runners/wasmrunner && du -h ./bin/wasmrunner.wasm

  run-plugin-config:
    env:
      CONFIG_FILE_PATH: ./testers/config/plugin.config.yaml
    cmds:
      - go run ./src

  run-phpcli-config:
    env:
      CONFIG_FILE_PATH: ./testers/config/phpcli.config.yaml
    cmds:
      - ./bin/events-bridge

  run-wasmrunner-config:
    env:
      CONFIG_FILE_PATH: ./testers/config/wasmrunner.config.yaml
    cmds:
      - ./bin/events-bridge

  run-mqtt-to-http:
    cmds:
      - cat ./testers/config/concurrently/mqtt-to-http.yaml | ./testers/bin/concurrently

  run-pgsql-to-http:
    cmds:
      - cat ./testers/config/concurrently/pgsql-to-http.yaml | ./testers/bin/concurrently

  run-nats-wasm-http:
    cmds:
      - cat ./testers/config/concurrently/nats-wasm-http.yaml | ./testers/bin/concurrently

  run-nats-jlo-http:
    cmds:
      - cat ./testers/config/concurrently/nats-jlo-http.yaml | ./testers/bin/concurrently

  run-nats-jlo-nats:
    cmds:
      - cat ./testers/config/concurrently/nats-jlo-nats.yaml | ./testers/bin/concurrently

  run-gptrunner-config:
    cmds:
      - cat ./testers/config/concurrently/gptrunner.yaml | ./testers/bin/concurrently

  run-kafka-jlo-kafka:
    cmds:
      - cat ./testers/config/concurrently/kafka-jlo-kafka.yaml | ./testers/bin/concurrently

  run-redis-jlo-redis:
    cmds:
      - cat ./testers/config/concurrently/redis-jlo-redis.yaml | ./testers/bin/concurrently

  run-redisstream-jlo-redisstream:
    cmds:
      - cat ./testers/config/concurrently/redis-stream-jlo-redis-stream.yaml | ./testers/bin/concurrently
