// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_STARTUP     Status = 1
	Status_STATUS_READY       Status = 3
	Status_STATUS_ERROR       Status = 4
	Status_STATUS_SHUTDOWN    Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_STARTUP",
		3: "STATUS_READY",
		4: "STATUS_ERROR",
		5: "STATUS_SHUTDOWN",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_STARTUP":     1,
		"STATUS_READY":       3,
		"STATUS_ERROR":       4,
		"STATUS_SHUTDOWN":    5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type Result int32

const (
	Result_RESULT_UNSPECIFIED Result = 0
	Result_RESULT_SUCCESS     Result = 1
	Result_RESULT_ERROR       Result = 2
	Result_RESULT_ASYNC       Result = 3
)

// Enum value maps for Result.
var (
	Result_name = map[int32]string{
		0: "RESULT_UNSPECIFIED",
		1: "RESULT_SUCCESS",
		2: "RESULT_ERROR",
		3: "RESULT_ASYNC",
	}
	Result_value = map[string]int32{
		"RESULT_UNSPECIFIED": 0,
		"RESULT_SUCCESS":     1,
		"RESULT_ERROR":       2,
		"RESULT_ASYNC":       3,
	}
)

func (x Result) Enum() *Result {
	p := new(Result)
	*p = x
	return p
}

func (x Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Result) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[1].Descriptor()
}

func (Result) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[1]
}

func (x Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Result.Descriptor instead.
func (Result) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Config) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type StatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReq) Reset() {
	*x = StatusReq{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReq) ProtoMessage() {}

func (x *StatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReq.ProtoReflect.Descriptor instead.
func (*StatusReq) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

type StatusRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=eventsbridge.plugin.v1.Status" json:"status,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRes) Reset() {
	*x = StatusRes{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRes) ProtoMessage() {}

func (x *StatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRes.ProtoReflect.Descriptor instead.
func (*StatusRes) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *StatusRes) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *StatusRes) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type ShutdownReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wait          *string                `protobuf:"bytes,1,opt,name=wait,proto3,oneof" json:"wait,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownReq) Reset() {
	*x = ShutdownReq{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownReq) ProtoMessage() {}

func (x *ShutdownReq) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownReq.ProtoReflect.Descriptor instead.
func (*ShutdownReq) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ShutdownReq) GetWait() string {
	if x != nil && x.Wait != nil {
		return *x.Wait
	}
	return ""
}

type ShutdownRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRes) Reset() {
	*x = ShutdownRes{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRes) ProtoMessage() {}

func (x *ShutdownRes) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRes.ProtoReflect.Descriptor instead.
func (*ShutdownRes) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

type PluginMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginMessage) Reset() {
	*x = PluginMessage{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMessage) ProtoMessage() {}

func (x *PluginMessage) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMessage.ProtoReflect.Descriptor instead.
func (*PluginMessage) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *PluginMessage) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *PluginMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PluginMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TargetRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetRes) Reset() {
	*x = TargetRes{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetRes) ProtoMessage() {}

func (x *TargetRes) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetRes.ProtoReflect.Descriptor instead.
func (*TargetRes) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

type SourceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*Config              `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceReq) Reset() {
	*x = SourceReq{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceReq) ProtoMessage() {}

func (x *SourceReq) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceReq.ProtoReflect.Descriptor instead.
func (*SourceReq) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *SourceReq) GetConfigs() []*Config {
	if x != nil {
		return x.Configs
	}
	return nil
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x16eventsbridge.plugin.v1\"2\n" +
	"\x06Config\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\v\n" +
	"\tStatusReq\"h\n" +
	"\tStatusRes\x126\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1e.eventsbridge.plugin.v1.StatusR\x06status\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"/\n" +
	"\vShutdownReq\x12\x17\n" +
	"\x04wait\x18\x01 \x01(\tH\x00R\x04wait\x88\x01\x01B\a\n" +
	"\x05_wait\"\r\n" +
	"\vShutdownRes\"\xc5\x01\n" +
	"\rPluginMessage\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12O\n" +
	"\bmetadata\x18\x02 \x03(\v23.eventsbridge.plugin.v1.PluginMessage.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\v\n" +
	"\tTargetRes\"E\n" +
	"\tSourceReq\x128\n" +
	"\aconfigs\x18\x01 \x03(\v2\x1e.eventsbridge.plugin.v1.ConfigR\aconfigs*m\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_STARTUP\x10\x01\x12\x10\n" +
	"\fSTATUS_READY\x10\x03\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x04\x12\x13\n" +
	"\x0fSTATUS_SHUTDOWN\x10\x05*X\n" +
	"\x06Result\x12\x16\n" +
	"\x12RESULT_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eRESULT_SUCCESS\x10\x01\x12\x10\n" +
	"\fRESULT_ERROR\x10\x02\x12\x10\n" +
	"\fRESULT_ASYNC\x10\x032\xb7\x03\n" +
	"\rPluginService\x12N\n" +
	"\x06Status\x12!.eventsbridge.plugin.v1.StatusReq\x1a!.eventsbridge.plugin.v1.StatusRes\x12T\n" +
	"\bShutdown\x12#.eventsbridge.plugin.v1.ShutdownReq\x1a#.eventsbridge.plugin.v1.ShutdownRes\x12T\n" +
	"\x06Source\x12!.eventsbridge.plugin.v1.SourceReq\x1a%.eventsbridge.plugin.v1.PluginMessage0\x01\x12V\n" +
	"\x06Runner\x12%.eventsbridge.plugin.v1.PluginMessage\x1a%.eventsbridge.plugin.v1.PluginMessage\x12R\n" +
	"\x06Target\x12%.eventsbridge.plugin.v1.PluginMessage\x1a!.eventsbridge.plugin.v1.TargetResB<Z:github.com/sandrolain/events-bridge/src/plugin/proto;protob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_plugin_proto_goTypes = []any{
	(Status)(0),           // 0: eventsbridge.plugin.v1.Status
	(Result)(0),           // 1: eventsbridge.plugin.v1.Result
	(*Config)(nil),        // 2: eventsbridge.plugin.v1.Config
	(*StatusReq)(nil),     // 3: eventsbridge.plugin.v1.StatusReq
	(*StatusRes)(nil),     // 4: eventsbridge.plugin.v1.StatusRes
	(*ShutdownReq)(nil),   // 5: eventsbridge.plugin.v1.ShutdownReq
	(*ShutdownRes)(nil),   // 6: eventsbridge.plugin.v1.ShutdownRes
	(*PluginMessage)(nil), // 7: eventsbridge.plugin.v1.PluginMessage
	(*TargetRes)(nil),     // 8: eventsbridge.plugin.v1.TargetRes
	(*SourceReq)(nil),     // 9: eventsbridge.plugin.v1.SourceReq
	nil,                   // 10: eventsbridge.plugin.v1.PluginMessage.MetadataEntry
}
var file_plugin_proto_depIdxs = []int32{
	0,  // 0: eventsbridge.plugin.v1.StatusRes.status:type_name -> eventsbridge.plugin.v1.Status
	10, // 1: eventsbridge.plugin.v1.PluginMessage.metadata:type_name -> eventsbridge.plugin.v1.PluginMessage.MetadataEntry
	2,  // 2: eventsbridge.plugin.v1.SourceReq.configs:type_name -> eventsbridge.plugin.v1.Config
	3,  // 3: eventsbridge.plugin.v1.PluginService.Status:input_type -> eventsbridge.plugin.v1.StatusReq
	5,  // 4: eventsbridge.plugin.v1.PluginService.Shutdown:input_type -> eventsbridge.plugin.v1.ShutdownReq
	9,  // 5: eventsbridge.plugin.v1.PluginService.Source:input_type -> eventsbridge.plugin.v1.SourceReq
	7,  // 6: eventsbridge.plugin.v1.PluginService.Runner:input_type -> eventsbridge.plugin.v1.PluginMessage
	7,  // 7: eventsbridge.plugin.v1.PluginService.Target:input_type -> eventsbridge.plugin.v1.PluginMessage
	4,  // 8: eventsbridge.plugin.v1.PluginService.Status:output_type -> eventsbridge.plugin.v1.StatusRes
	6,  // 9: eventsbridge.plugin.v1.PluginService.Shutdown:output_type -> eventsbridge.plugin.v1.ShutdownRes
	7,  // 10: eventsbridge.plugin.v1.PluginService.Source:output_type -> eventsbridge.plugin.v1.PluginMessage
	7,  // 11: eventsbridge.plugin.v1.PluginService.Runner:output_type -> eventsbridge.plugin.v1.PluginMessage
	8,  // 12: eventsbridge.plugin.v1.PluginService.Target:output_type -> eventsbridge.plugin.v1.TargetRes
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	file_plugin_proto_msgTypes[2].OneofWrappers = []any{}
	file_plugin_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
