name: events-bridge-localtest
version: "3.8"
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222" # Client connections
      - "8222:8222" # HTTP monitoring
    restart: unless-stopped
    volumes:
      - ./nats/nats-server.conf:/nats-server.conf
    command: ["-c", "/nats-server.conf"]

  emqx:
    image: emqx/emqx:latest
    ports:
      - "1883:1883" # MQTT
      - "8083:8083" # MQTT over WebSocket
      - "8084:8084" # MQTT over SSL
      - "18083:18083" # Dashboard
    restart: unless-stopped

  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    restart: unless-stopped
