name: events-bridge-localtest
version: "3.8"
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222" # Client connections
      - "8222:8222" # HTTP monitoring
    restart: unless-stopped
    volumes:
      - ./nats/nats-server.conf:/nats-server.conf
    command: ["-c", "/nats-server.conf"]

  emqx:
    image: emqx/emqx:latest
    ports:
      - "1883:1883" # MQTT
      - "8083:8083" # MQTT over WebSocket
      - "8084:8084" # MQTT over SSL
      - "18083:18083" # Dashboard
    restart: unless-stopped

  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped

  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__PATH=/data/gitea/gitea.db
      - GITEA__server__ROOT_URL=http://localhost:3000/
    restart: always
    ports:
      - "3000:3000" # Web UI
      - "2222:2222" # SSH
    volumes:
      - gitea-data:/data
      - gitea-config:/etc/gitea

volumes:
  gitea-data:
  gitea-config:
