plugins:
  - name: "example-plugin"
    exec: "./testers/bin/plugin"
    protocol: "tcp"
    output: true
    delay: 1000ms

source:
  type: "plugin"
  plugin:
    name: "example-plugin"

target:
  type: "plugin"
  plugin:
    name: "example-plugin"

runner:
  type: "plugin"
  plugin:
    name: "example-plugin"
