commands:
  - name: redistarget-stream
    cmd: "./testers/bin/redistool"
    args:
      [
        "serve",
        "--address",
        "localhost:6379",
        "--stream",
        "test.stream.out",
        "--group",
        "test-consumer-group",
        "--consumer",
        "consumer-1",
        "--dataKey",
        "data",
      ]
    restartTries: 0
  - name: task
    cmd: "./bin/events-bridge"
    env:
      EB_CONFIG_CONTENT: |
        source:
          type: "redis"
          options:
            address: "localhost:6379"
            stream: "test.stream.in"
            consumerGroup: "bridge-consumer-group"
            consumerName: "bridge-consumer-1"
            streamDataKey: "data"

        target:
          type: "redis"
          options:
            address: "localhost:6379"
            stream: "test.stream.out"
            streamDataKey: "data"

        runners:
          - type: "jsonlogic"
            options:
              logic: |
                {
                  "and": [
                    { ">=": [ { "var": "temperature" }, 20 ] },
                    { "<=": [ { "var": "temperature" }, 30 ] },
                    { ">=": [ { "var": "humidity" }, 30 ] },
                    { "<=": [ { "var": "humidity" }, 70 ] }
                  ]
                }
              preservePayload: true
              timeout: "5s"
    args: []
    restartTries: 0
  - name: redissource-stream
    cmd: "./testers/bin/redistool"
    args:
      [
        "send",
        "--address",
        "localhost:6379",
        "--stream",
        "test.stream.in",
        "--interval",
        "2s",
        "--payload",
        '{"temperature": 25.5, "humidity": 60, "location": "sensor-001", "timestamp": "{nowtime}"}',
      ]
    restartTries: 0
killOthers: true
