commands:
  - cmd: "./testers/bin/httptarget"
    args: ["--address", "0.0.0.0:8081"]
    restart: false
  - cmd: "./bin/events-bridge"
    env:
      CONFIG_FILE_PATH: ./testers/config/bridge/gptrunner.config.yaml
    args: []
    restart: false
  - cmd: "./testers/bin/httpsource"
    args: ["--path", "/event", "--testpayload", "sentiment", "--interval", "1s"]
    restart: false
killOnExit: true
