commands:
  - name: kafkatarget
    cmd: "./testers/bin/kafkatarget"
    args: ["--brokers", "localhost:9092", "--topic", "test.topic.out"]
    restart: false
  - name: task
    cmd: "./bin/events-bridge"
    env:
      CONFIG_FILE_PATH: ./testers/config/bridge/kafka-jlo-kafka.config.yaml
    args: []
    restart: false
  - name: kafkasource
    cmd: "./testers/bin/kafkasource"
    args:
      [
        "--brokers",
        "localhost:9092",
        "--topic",
        "test.topic.in",
        "--interval",
        "1s",
        "--payload",
        '{"a":10, "b":20, "date": "{nowtime}"}',
      ]
    restart: false
killOnExit: true
