commands:
  - name: httptarget
    cmd: "./testers/bin/httptarget"
    args: []
    restart: false
  - name: task
    cmd: "./bin/events-bridge"
    env:
      CONFIG_FILE_PATH: ./testers/config/bridge/mqtt-to-http.config.yaml
    args: []
    restart: false
  - name: mqttsource
    cmd: "./testers/bin/mqttsource"
    args: []
    restart: false
killOnExit: true
