commands:
  - name: httptarget
    cmd: "./testers/bin/httptarget"
    args: []
    restart: false
  - name: task
    cmd: "./bin/events-bridge"
    env:
      CONFIG_FILE_PATH: ./testers/config/bridge/pgsql-to-http.config.yaml
    args: []
    restart: false
  - name: pgsqlsource
    cmd: "./testers/bin/pgsqlsource"
    args: []
    restart: false
killOnExit: true
