commands:
  - name: redistarget
    cmd: "./testers/bin/redistarget"
    args: ["--address", "localhost:6379", "--channel", "test.channel.out"]
    restart: false
  - name: task
    cmd: "./bin/events-bridge"
    env:
      CONFIG_FILE_PATH: ./testers/config/bridge/redis-jlo-redis.config.yaml
    args: []
    restart: false
  - name: redissource
    cmd: "./testers/bin/redissource"
    args:
      [
        "--address",
        "localhost:6379",
        "--channel",
        "test.channel.in",
        "--interval",
        "1s",
        "--payload",
        '{"a":10, "b":20, "date": "{nowtime}"}',
      ]
    restart: false
killOnExit: true
