commands:
  - name: http-target
    cmd: "./testers/bin/httptool"
    args: ["serve"]
    restartTries: 0
  - name: task
    cmd: "./bin/events-bridge"
    env:
      EB_CONFIG_FILE_PATH: ./testers/config/bridge/git-wasm-http.config.yaml
    args: []
    restartTries: 0
  - name: git-source
    cmd: "./testers/bin/gittool"
    args:
      [
        "send",
        "--remote",
        "http://localhost:3000/testuser/testrepo.git",
        "--branch",
        "main",
        "--username",
        "testuser",
        "--password",
        "testpass",
        "--interval",
        "4s",
      ]
    restartTries: 0
killOthers: true
