commands:
  - name: http-target
    cmd: "./testers/bin/httptool"
    args: ["serve"]
    restartTries: 0
  - name: task
    cmd: "./bin/events-bridge"
    env:
      EB_CONFIG_CONTENT: |
        source:
          type: "git"
          options:
            remote_url: "http://localhost:3000/testuser/testrepo.git"
            username: "testuser"
            password: "testpass"
            remote: "origin"
            branch: "main"
            poll_interval: 10
            # subdir: "optional/subdir"

        target:
          type: "http"
          options:
            method: "POST"
            url: "http://localhost:8080/api/data"

        runner:
          type: "wasm"
          options:
            path: "./testers/bin/wasmrunner.wasm"
    args: []
    restartTries: 0
  - name: git-source
    cmd: "./testers/bin/gittool"
    args:
      [
        "send",
        "--remote",
        "http://localhost:3000/testuser/testrepo.git",
        "--branch",
        "main",
        "--username",
        "testuser",
        "--password",
        "testpass",
        "--interval",
        "4s",
      ]
    restartTries: 0
killOthers: true
