commands:
  - name: http-target
    cmd: "./testers/bin/httptool"
    args: ["serve"]
    restartTries: 0
  - name: task
    cmd: "./bin/events-bridge"
    env:
      EB_CONFIG_CONTENT: |
        source:
          type: "http"
          http:
            address: "localhost:8080"
            method: "POST"
            path: "/event"

        target:
          type: "http"
          http:
            method: "POST"
            url: "http://localhost:9090/api/data"
          routines: 8

        runner:
          type: "wasm"
          wasm:
            path: "./testers/bin/wasmrunner.wasm"
          routines: 8
    args: []
    restartTries: 0
  - name: http-source
    cmd: "./testers/bin/httptool"
    args: ["send", "--interval", "1000us", "--payload", "{counter} - {nowtime}"]
    startAfter: "5s"
killOthers: true
