commands:
  - name: kafka-target
    cmd: "./testers/bin/kafkatool"
    args: ["serve", "--brokers", "localhost:9092", "--topic", "test.topic.out"]
    restartTries: 0
  - name: task
    cmd: "./bin/events-bridge"
    env:
      EB_CONFIG_CONTENT: |
        source:
          type: "kafka"
          kafka:
            brokers: ["localhost:9092"]
            group_id: "test-group"
            topic: "test.topic.in"

        target:
          type: "kafka"
          kafka:
            brokers: ["localhost:9092"]
            group_id: "test-group"
            topic: "test.topic.out"

        runner:
          type: "jsonlogic"
          options:
            path: "./testers/config/bridge/jsonlogic-rule.json"
          # you can change the path or the rule as needed
    args: []
    restartTries: 0
  - name: kafka-source
    cmd: "./testers/bin/kafkatool"
    args:
      [
        "send",
        "--brokers",
        "localhost:9092",
        "--topic",
        "test.topic.in",
        "--interval",
        "1s",
        "--payload",
        '{"a":10, "b":20, "date": "{nowtime}"}',
      ]
    restartTries: 0
killOthers: true
