commands:
  - name: kafka-target
    cmd: "./testers/bin/kafkatool"
    args: ["serve", "--brokers", "localhost:9092", "--topic", "test.topic.out"]
    restartTries: 0
  - name: task
    cmd: "./bin/events-bridge"
    env:
      CONFIG_FILE_PATH: ./testers/config/bridge/kafka-jlo-kafka.config.yaml
    args: []
    restartTries: 0
  - name: kafka-source
    cmd: "./testers/bin/kafkatool"
    args:
      [
        "send",
        "--brokers",
        "localhost:9092",
        "--topic",
        "test.topic.in",
        "--interval",
        "1s",
        "--payload",
        '{"a":10, "b":20, "date": "{nowtime}"}',
      ]
    restartTries: 0
killOthers: true
