commands:
  - name: http-target
    cmd: "./testers/bin/httptool"
    args: ["serve"]
    restartTries: 0
  - name: task
    cmd: "./bin/events-bridge"
    env:
      EB_CONFIG_CONTENT: |
        source:
          type: "mqtt"
          mqtt:
            address: "localhost:1883"
            topic: "test/topic"
            client_id: "mqtt-to-http-client"
            consumer_group: "mqtt-to-http-group"

        target:
          type: "http"
          http:
            method: "POST"
            url: "http://localhost:8080/api/data"
          routines: 8

        runner:
          type: "wasm"
          options:
            path: "./testers/bin/wasmrunner.wasm"
          routines: 8
    args: []
    restartTries: 0
  - name: mqtt-source
    cmd: "./testers/bin/mqtttool"
    args: ["send", "--interval", "500us", "--payload", "{counter} - {nowtime}"]
    startAfter: "2s"
killOthers: true
