commands:
  - name: nats-target
    cmd: "./testers/bin/natstool"
    args:
      ["serve", "--address", "localhost:4222", "--subject", "test.subject.out"]
    restartTries: 0
  - name: task
    cmd: "./bin/events-bridge"
    env:
      EB_CONFIG_FORMAT: "yaml"
      EB_CONFIG_CONTENT: |
        source:
          type: "nats"
          nats:
            address: "localhost:4222"
            subject: "test.subject.in"
        target:
          type: "nats"
          nats:
            address: "localhost:4222"
            subject: "test.subject.out"
          routines: 8
        runner:
          type: "jsonlogic"
          jsonlogic:
            path: "./testers/config/bridge/jsonlogic-rule.json"
            preservePayload: true
          routines: 8
    args: []
    restartTries: 0
  - name: nats-source
    cmd: "./testers/bin/natstool"
    args:
      [
        "send",
        "--address",
        "localhost:4222",
        "--subject",
        "test.subject.in",
        "--interval",
        "1000us",
        "--payload",
        '{"a":10, "b":20, "date": "{nowtime}", "count": {counter}}',
      ]
    restartTries: 0
    startAfter: "2s"
    duration: "3s"
    silent: true
killOthers: true
