commands:
  - name: http-target
    cmd: "./testers/bin/httptool"
    args: ["serve"]
    restartTries: 0
  - name: task
    cmd: "./bin/events-bridge"
    env:
      EB_CONFIG_CONTENT: |
        source:
          type: "nats"
          nats:
            address: "localhost:4222"
            subject: "test.subject"

        target:
          type: "http"
          http:
            method: "POST"
            url: "http://localhost:8080/api/data"

        runner:
          type: "wasm"
          wasm:
            path: "./testers/bin/wasmrunner.wasm"
    args: []
    restartTries: 0
  - name: nats-source
    cmd: "./testers/bin/natstool"
    args: ["send", "--interval", "50ms", "--stream", "test-stream"]
    restartTries: 0
killOthers: true
