commands:
  - name: http-target
    cmd: "./testers/bin/httptool"
    args: ["serve"]
    restartTries: 0
  - name: task
    cmd: "./bin/events-bridge"
    env:
      EB_CONFIG_FILE_PATH: ./testers/config/bridge/nats-jlo-http.config.yaml
    args: []
    restartTries: 0
  - name: nats-source
    cmd: "./testers/bin/natstool"
    args:
      [
        "send",
        "--interval",
        "1s",
        "--payload",
        '{"a":10, "b":20, "date": "{nowtime}"}',
      ]
    restartTries: 0
killOthers: true
