commands:
  - name: nats-target
    cmd: "./testers/bin/natstool"
    args:
      ["serve", "--address", "localhost:4222", "--subject", "test.subject.out"]
    restartTries: 0
  - name: task
    cmd: "./bin/events-bridge"
    env:
      CONFIG_FILE_PATH: ./testers/config/bridge/nats-jlo-nats.config.yaml
    args: []
    restartTries: 0
    silent: true
  - name: nats-source
    cmd: "./testers/bin/natstool"
    args:
      [
        "send",
        "--address",
        "localhost:4222",
        "--subject",
        "test.subject.in",
        "--interval",
        "1000us",
        "--payload",
        '{"a":10, "b":20, "date": "{nowtime}", "count": {counter}}',
      ]
    restartTries: 0
    startAfter: "2s"
    duration: "3s"
    silent: true
killOthers: true
