commands:
  - name: http-target
    cmd: "./testers/bin/httptool"
    args: ["serve"]
    restartTries: 0
  - name: task
    cmd: "./bin/events-bridge"
    env:
      EB_CONFIG_CONTENT: |
        source:
          type: "nats"
          options:
            address: "localhost:4222"
            subject: "test.subject"

        target:
          type: "http"
          options:
            method: "POST"
            url: "http://localhost:8080/api/data"

        runner:
          type: "jsonlogic"
          options:
            logic: |
              {"+":[{"var":"a"},{"var":"b"}]}
            preservePayload: true
    args: []
    restartTries: 0
  - name: nats-source
    cmd: "./testers/bin/natstool"
    args:
      [
        "send",
        "--interval",
        "1s",
        "--payload",
        '{"a":10, "b":20, "date": "{nowtime}"}',
      ]
    restartTries: 0
killOthers: true
