commands:
  - name: http-target
    cmd: "./testers/bin/httptool"
    args: ["serve"]
    restartTries: 0
  - name: task
    cmd: "./bin/events-bridge"
    env:
      EB_CONFIG_CONTENT: |
        source:
          type: "pgsql"
          options:
            conn_string: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"
            table: "test_table"

        target:
          type: "http"
          options:
            method: "POST"
            url: "http://localhost:8080/api/data"

        runner:
          type: "wasm"
          options:
            path: "./testers/bin/wasmrunner.wasm"
    args: []
    restartTries: 0
  - name: pgsql-source
    cmd: "./testers/bin/pgsqltool"
    args: ["send"]
    restartTries: 0
killOthers: true
