commands:
  - name: redis-target
    cmd: "./testers/bin/redistool"
    args:
      ["serve", "--address", "localhost:6379", "--channel", "test.channel.out"]
    restartTries: 0
  - name: task
    cmd: "./bin/events-bridge"
    env:
      EB_CONFIG_CONTENT: |
        source:
          type: "redis"
          redis:
            address: "localhost:6379"
            channel: "test.channel.in"

        target:
          type: "redis"
          redis:
            address: "localhost:6379"
            channel: "test.channel.out"

        runner:
          type: "jsonlogic"
          options:
            path: "./testers/config/bridge/jsonlogic-rule.json"
          # you can change the path or the rule as needed
    args: []
    restartTries: 0
  - name: redis-source
    cmd: "./testers/bin/redistool"
    args:
      [
        "send",
        "--address",
        "localhost:6379",
        "--channel",
        "test.channel.in",
        "--interval",
        "1s",
        "--payload",
        '{"a":10, "b":20, "date": "{nowtime}"}',
      ]
    restartTries: 0
killOthers: true
