commands:
  - name: redistarget-stream
    cmd: "./testers/bin/redistool"
    args:
      [
        "serve",
        "--address",
        "localhost:6379",
        "--stream",
        "test.stream.out",
        "--group",
        "test-consumer-group",
        "--consumer",
        "consumer-1",
        "--dataKey",
        "data",
      ]
    restartTries: 0
  - name: task
    cmd: "./bin/events-bridge"
    env:
      CONFIG_FILE_PATH: ./testers/config/bridge/redis-stream-jlo-redis-stream.config.yaml
    args: []
    restartTries: 0
  - name: redissource-stream
    cmd: "./testers/bin/redistool"
    args:
      [
        "send",
        "--address",
        "localhost:6379",
        "--stream",
        "test.stream.in",
        "--interval",
        "2s",
        "--payload",
        '{"temperature": 25.5, "humidity": 60, "location": "sensor-001", "timestamp": "{nowtime}"}',
      ]
    restartTries: 0
killOthers: true
